/*
VIEW 1
Return for every call:
callid, calldate, how many teams where sent, the name of the dispatcher,
num of drivers, nums of paramedics, num of volunteers
*/
CREATE VIEW CALLS 
AS 
SELECT  CALLID, CALLDATE,  COUNT(DISTINCT(TEAMID)) AS TEAMS, 
        CONCAT(CONCAT(FIRSTNAME ,' '),LASTNAME) AS DISPATCHER_NAME, 
        COUNT(DISTINCT(DRIVERID)) AS DRIVERS, 
        COUNT(DISTINCT(PARAMEDICID)) AS PARAMEDICS, 
        COUNT(DISTINCT(VOLUNTEERID)) AS VOLUNTEERS
FROM CALLHELP 
NATURAL JOIN DISPATCHER 
JOIN PERSON ON PERSONID = DISPATCHERID
NATURAL JOIN SENDTEAM
NATURAL JOIN TEAM
NATURAL JOIN DRIVER
NATURAL JOIN PARTICIPANTPARAMEDIC
NATURAL JOIN PARTICIPANTVOLUNTEER
GROUP BY CALLID, CALLDATE,CONCAT(CONCAT(FIRSTNAME ,' '),LASTNAME)
ORDER BY CALLID, CALLDATE;


/*SELECT*/
SELECT * FROM CALLS;

/*
1
For every name of dispatcher return the num of calls he opened.
*/
SELECT DISPATCHER_NAME, COUNT(*) AS NUM_CALLS
FROM CALLS
GROUP BY DISPATCHER_NAME;

/*
2
return for every month how many calls there were.
*/
SELECT EXTRACT(MONTH FROM CALLDATE), COUNT(*) AS NUM_CALLS
FROM CALLS
GROUP BY EXTRACT(MONTH FROM CALLDATE)
ORDER BY EXTRACT(MONTH FROM CALLDATE);

                      
/*DROP*/
DROP VIEW CALLS;
