select * from donationItem;
select * from  ordering;
select * from  donation;
select * from donor;
select * from  storekeeper;
select * from  warehouse;
select * from  item;
select * from  person;
SELECT * FROM itemType  
